CREATE TABLE CAR_INFO
(
	CAR_ID INTEGER NOT NULL,
	MAKE VARCHAR(50) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	YEAR INTEGER NOT NULL,
	PRIMARY KEY(CAR_ID)
);

CREATE TABLE OBJ_FEATURES
(
	CAR_ID INTEGER NOT NULL,
	WARRANTY_BASIC VARCHAR(50),
	WARRANTY_DRIVETRAIN VARCHAR(50),
	WARRANTY_ROADSIDE VARCHAR(50),
	WARRANTY_RUST VARCHAR(50),
	WARRANTY_FREE_MAINTENANCE VARCHAR(50),
	WARRANTY_EV_BATTERY VARCHAR(50),
	WARRANTY_HYBRID_COMPONENT VARCHAR(50),
	IM_FRONT_HEAD_ROOM VARCHAR(50),
	IM_FRONT_HIP_ROOM VARCHAR(50),
	IM_FRONT_LEG_ROOM VARCHAR(50),
	IM_FRONT_SHOULDER_ROOM VARCHAR(50),
	IM_REAR_HIP_ROOM VARCHAR(50),
	IM_REAR_HEAD_ROOM VARCHAR(50),
	IM_REAR_LEG_ROOM VARCHAR(50),
	IM_REAR_SHOULDER_ROOM VARCHAR(50),
	EM_WIDTH VARCHAR(50),
	EM_HEIGHT VARCHAR(50),
	EM_LENGTH VARCHAR(50),
	EM_WHEEL_BASE VARCHAR(50),
	EM_FRONT_TRACK VARCHAR(50),
	EM_REAR_TRACK VARCHAR(50),
	EM_GROUND_CLEARANCE VARCHAR(50),
	WAC_EPA_INTERIOR_VOLUME VARCHAR(50),
	WAC_CURB_WEIGHT VARCHAR(50),
	WAC_CARGO_CAPACITY VARCHAR(50),
	WAC_MAXIMUM_TOWING_CAPACITY VARCHAR(50),
	WAC_ANGLE_OF_APPROACH VARCHAR(50),
	WAC_ANGLE_OF_DEPARTURE VARCHAR(50),
	WAC_MAXIMUM_CARGO_CAPACITY VARCHAR(50),
	WAC_GROSS_WEIGHT VARCHAR(50),
	WAC_DRAG_COEFFICIENT VARCHAR(50),
	WAC_MAXIMUM_PAYLOAD VARCHAR(50),
	EAP_BASE_ENGINE_SIZE VARCHAR(50),
	EAP_CAM_TYPE VARCHAR(50),
	EAP_CYLINDERS VARCHAR(50),
	EAP_VALVES VARCHAR(50),
	EAP_VALVE_TIMING VARCHAR(50),
	EAP_TORQUE VARCHAR(50),
	EAP_HORSEPOWER VARCHAR(50),
	EAP_TURNING_CIRCLE VARCHAR(50),
	FUEL_ENGINE_TYPE VARCHAR(50),
	FUEL_TYPE VARCHAR(50),
	FUEL_TANK_CAPACITY VARCHAR(50),
	FUEL_RANGE_IN_MILES VARCHAR(50),
	FUEL_EPA_MILEAGE_EST VARCHAR(50),
	DT_DRIVE_TYPE VARCHAR(50),
	DT_TRANSMISSION VARCHAR(50),
	PRICE INTEGER,
	PRIMARY KEY(CAR_ID),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE SUBJ_FEATURES
(
	CAR_ID INTEGER NOT NULL,
	FUELEFFICIENT FLOAT,
	TRUNK FLOAT,
	OUTDOOR FLOAT,
	FAMILY FLOAT,
	LUXAPPEARANCE FLOAT,
	SOUND FLOAT,
	INFOCENTER FLOAT,
	WINTER FLOAT,
	CABINROOMY FLOAT,
	POWER FLOAT,
	SPORTY FLOAT,
	SIMPLE FLOAT,
	VISIBILITY FLOAT,
	RELIABLE FLOAT,
	COMFSEATS FLOAT,
	SMOOTH FLOAT,
	QUIETNESS FLOAT,
	VALUE FLOAT,
	APPEARANCE FLOAT,
	USERSATISFACTION FLOAT,
	PRIMARY KEY(CAR_ID),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE SUSPENSION
(
	CAR_ID INTEGER NOT NULL,
	SUSPENSION VARCHAR(50) NOT NULL,
	PRIMARY KEY(CAR_ID, SUSPENSION),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_COLOR
(
	CAR_ID INTEGER NOT NULL,
	EXT_COLOR VARCHAR(75) NOT NULL,
	PRIMARY KEY(CAR_ID, EXT_COLOR),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_COLOR
(
	CAR_ID INTEGER NOT NULL,
	INT_COLOR VARCHAR(75) NOT NULL,
	PRIMARY KEY(CAR_ID, INT_COLOR),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_FRONT_SEATS
(
	CAR_ID INTEGER NOT NULL,
	FRONT_SEATS VARCHAR(60) NOT NULL,
	PRIMARY KEY(CAR_ID, FRONT_SEATS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_INSTRUMENTATION
(
	CAR_ID INTEGER NOT NULL,
	INSTRUMENTATION VARCHAR(30) NOT NULL,
	PRIMARY KEY(CAR_ID, INSTRUMENTATION),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_MEMORIZED_SETTINGS
(
	CAR_ID INTEGER NOT NULL,
	MEMORIZED_SETTINGS VARCHAR(50) NOT NULL,
	PRIMARY KEY(CAR_ID, MEMORIZED_SETTINGS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_REAR_SEATS
(
	CAR_ID INTEGER NOT NULL,
	REAR_SEATS VARCHAR(60) NOT NULL,
	PRIMARY KEY(CAR_ID, REAR_SEATS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_COMFORT
(
	CAR_ID INTEGER NOT NULL,
	COMFORT VARCHAR(50) NOT NULL,
	PRIMARY KEY(CAR_ID, COMFORT),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_CONVENIENCE
(
	CAR_ID INTEGER NOT NULL,
	CONVENIENCE VARCHAR(75) NOT NULL,
	PRIMARY KEY(CAR_ID, CONVENIENCE),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_POWER_FEATURES
(
	CAR_ID INTEGER NOT NULL,
	POWER_FEATURES VARCHAR(75) NOT NULL,
	PRIMARY KEY(CAR_ID, POWER_FEATURES),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_ENTERTAINMENT
(
	CAR_ID INTEGER NOT NULL,
	ENTERTAINMENT VARCHAR(60) NOT NULL,
	PRIMARY KEY(CAR_ID, ENTERTAINMENT),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE INT_TELEMATICS
(
	CAR_ID INTEGER NOT NULL,
	TELEMATICS VARCHAR(70) NOT NULL,
	PRIMARY KEY(CAR_ID, TELEMATICS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_BODY
(
	CAR_ID INTEGER NOT NULL,
	BODY VARCHAR(15) NOT NULL,
	PRIMARY KEY(CAR_ID, BODY),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_TOWING_AND_HAULING
(
	CAR_ID INTEGER NOT NULL,
	TOWING_AND_HAULING VARCHAR(20) NOT NULL,
	PRIMARY KEY(CAR_ID, TOWING_AND_HAULING),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_TIRES_AND_WHEELS
(
	CAR_ID INTEGER NOT NULL,
	TIRES_AND_WHEELS VARCHAR(35) NOT NULL,
	PRIMARY KEY(CAR_ID, TIRES_AND_WHEELS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_DOORS
(
	CAR_ID INTEGER NOT NULL,
	DOORS VARCHAR(40) NOT NULL,
	PRIMARY KEY(CAR_ID, DOORS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_ROOF_AND_GLASS
(
	CAR_ID INTEGER NOT NULL,
	ROOF_AND_GLASS VARCHAR(45) NOT NULL,
	PRIMARY KEY(CAR_ID, ROOF_AND_GLASS),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE EXT_TRUCK_FEATURES
(
	CAR_ID INTEGER NOT NULL,
	TRUCK_FEATURES VARCHAR(40) NOT NULL,
	PRIMARY KEY(CAR_ID, TRUCK_FEATURES),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);

CREATE TABLE SAFETY
(
	CAR_ID INTEGER NOT NULL,
	SAFETY VARCHAR(80) NOT NULL,
	PRIMARY KEY(CAR_ID, SAFETY),
	FOREIGN KEY(CAR_ID) REFERENCES CAR_INFO ON DELETE CASCADE
);
